// <auto-generated />
using System;
using Assignment2.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Assignment2.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Assignment2.Models.Car", b =>
                {
                    b.Property<string>("Model")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CompanyName");

                    b.Property<int?>("UserId");

                    b.HasKey("Model");

                    b.HasIndex("CompanyName");

                    b.HasIndex("UserId");

                    b.ToTable("Cars");
                });

            modelBuilder.Entity("Assignment2.Models.Company", b =>
                {
                    b.Property<string>("Name")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CarModel");

                    b.HasKey("Name");

                    b.HasIndex("CarModel");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("Assignment2.Models.Project", b =>
                {
                    b.Property<string>("Name")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("SkillName");

                    b.Property<int?>("UserId");

                    b.HasKey("Name");

                    b.HasIndex("SkillName");

                    b.HasIndex("UserId");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("Assignment2.Models.Skill", b =>
                {
                    b.Property<string>("Name")
                        .ValueGeneratedOnAdd();

                    b.HasKey("Name");

                    b.ToTable("Skills");
                });

            modelBuilder.Entity("Assignment2.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Assignment2.Models.Car", b =>
                {
                    b.HasOne("Assignment2.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyName");

                    b.HasOne("Assignment2.Models.User", "User")
                        .WithMany("Cars")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("Assignment2.Models.Company", b =>
                {
                    b.HasOne("Assignment2.Models.Car")
                        .WithMany("Companies")
                        .HasForeignKey("CarModel");
                });

            modelBuilder.Entity("Assignment2.Models.Project", b =>
                {
                    b.HasOne("Assignment2.Models.Skill")
                        .WithMany("Projects")
                        .HasForeignKey("SkillName");

                    b.HasOne("Assignment2.Models.User")
                        .WithMany("Projects")
                        .HasForeignKey("UserId");
                });
#pragma warning restore 612, 618
        }
    }
}
